const CharacterList = [
  {
    master_character_id: 0,
    character_name: 'Huntsman Hyrum',
    cost: 0,
    rarity: 'Commoner',
    description:
      'Before he was Aja of Resolute, Hyrum was young, brash and more concerned with drink than politics. This young Hyrum cares enough to feed his fellow survivors, just not for free.',
    type: 'Character',
    passive: 'Haiq-ken Resolution',
    passive_detail: `Gains 10% armor when he does a Special Attack or is critically hit.`,
    base_damage: 275,
    base_health: 180,
    chance_to_hit: 0.8,
    crit_chance: 0,
    crit_damage: 1.5,
  },
  {
    master_character_id: 1,
    character_name: 'Blackguard Clara',
    cost: 0,
    rarity: 'Commoner',
    description:
      'Conscripted into the Wren Blackguard, this Clara was pulled into the present before discovering her cleric abilities. Instead, Clara is a battle hardened warrior and brutal on the battlefield.',
    type: 'Character',
    passive: 'Blackwren Retribution',
    passive_detail: `Being critically hit, Clara's next strike is a guarenteed critical.`,
    base_damage: 225,
    base_health: 230,
    chance_to_hit: 0.8,
    crit_chance: 0,
    crit_damage: 1.5,
  },
  {
    master_character_id: 2,
    character_name: 'Marksmen Rennex',
    cost: 0,
    rarity: 'Commoner',
    description: `Discovered on the brink of death, this Rennex was taken in by the mad scientist, Damaris, who used Rennex's inventions to create an army of homebrew Marksmen. What survived of Rennex is gone and what remains is just a pawn in the war against hell.`,
    type: 'Character',
    passive: 'Unknown',
    passive_detail: 'In idle combat, Rennex will use his Special Attacks 5% more often.',
    base_damage: 215,
    base_health: 195,
    chance_to_hit: 0.87,
    crit_chance: 0,
    crit_damage: 1.5,
  },
  {
    master_character_id: 3,
    character_name: 'Masis Currey',
    cost: 0,
    rarity: 'Commoner',
    description: '',
    type: 'Character',
    passive: 'Unknown',
    passive_detail: '',
    base_damage: 205,
    base_health: 185,
    chance_to_hit: 0.89,
    crit_chance: 0,
    crit_damage: 1.5,
  },
  {
    master_character_id: 4,
    character_name: 'Renegade Llewelyn',
    cost: 0,
    rarity: 'Commoner',
    description: '.',
    type: 'Character',
        passive: 'Unknown',
    passive_detail: '',
    base_damage: 235,
    base_health: 160,
    chance_to_hit: 0.88,
    crit_chance: 0,
    crit_damage: 1.5,
  },
  {
    master_character_id: 5,
    character_name: `Hand's Daetoris`,
    cost: 0,
    rarity: 'Commoner',
    description: `Ex-professor of the Blueshore Conservatory, the shadow of Daetoris' past dealings with the Guiding Hand still haunt him.`,
    type: 'Character',
        passive: 'Unknown',
    passive_detail: '',
    base_damage: 250,
    base_health: 185,
    chance_to_hit: 0.85,
    crit_chance: 0,
    crit_damage: 1.5,
  },
  {
    master_character_id: 11,
    character_name: 'Renegade',
    cost: 0,
    rarity: 'Commoner',
    description: '.',
    type: 'Character',
        passive: 'Unknown',
    passive_detail: '',
    base_damage: 270,
    base_health: 200,
    chance_to_hit: 0.8,
    crit_chance: 0,
    crit_damage: 1.5,
  },
  // Add more card objects as needed
]

module.exports = CharacterList
