const CharacterList = [
  {
    master_character_id: 0,
    character_name: 'Huntsman Hyrum',
    cost: 0,
    rarity: 'Commoner',
    description:
      'Before Hyrum was Aja of Resolute, he was a skilled warrior and folk hero of his people.',
    type: 'Character',
    unique_skill: 'Unknown',
    base_damage: 275,
    base_health: 180,
    chance_to_hit: 0.8,
    crit_chance: 0,
    crit_damage: 1.5,
  },
  {
    master_character_id: 1,
    character_name: 'Blackguard Clara',
    cost: 0,
    rarity: 'Commoner',
    description:
      'Servants of the nation, Clara served as a Wren Blackguard for decade, before deserting her post and discovering her cleric power.',
    type: 'Character',
    unique_skill: 'Unknown',
    base_damage: 225,
    base_health: 230,
    chance_to_hit: 0.8,
    crit_chance: 0,
    crit_damage: 2,
  },
  {
    master_character_id: 2,
    character_name: 'Marksmen Rennex',
    cost: 0,
    rarity: 'Commoner',
    description: `Discovered on the brink of death, Rennex was taken by Damaris and his inventions were turned against him. Rennex is now just another pawn in the mad scientist's war against hell.`,
    type: 'Character',
    unique_skill: 'Unknown',
    base_damage: 215,
    base_health: 195,
    chance_to_hit: 0.87,
    crit_chance: 0,
    crit_damage: 1.5,
  },
  {
    master_character_id: 3,
    character_name: 'Masis Currey',
    cost: 0,
    rarity: 'Commoner',
    description: '',
    type: 'Character',
    unique_skill: 'Unknown',
    base_damage: 205,
    base_health: 185,
    chance_to_hit: 0.89,
    crit_chance: 0,
    crit_damage: 1.5,
  },
  {
    master_character_id: 4,
    character_name: 'Renegade Llewelyn',
    cost: 0,
    rarity: 'Commoner',
    description: '.',
    type: 'Character',
    unique_skill: 'Unknown',
    base_damage: 235,
    base_health: 160,
    chance_to_hit: 0.88,
    crit_chance: 0,
    crit_damage: 1.5,
  },
  {
    master_character_id: 5,
    character_name: `Hand's Daetoris`,
    cost: 0,
    rarity: 'Commoner',
    description: `Ex-professor of the Blueshore Conservatory, the shadow of Daetoris' past dealings with the Guiding Hand still haunt him.`,
    type: 'Character',
    unique_skill: 'Unknown',
    base_damage: 250,
    base_health: 185,
    chance_to_hit: 0.85,
    crit_chance: 0,
    crit_damage: 1.5,
  },
  {
    master_character_id: 11,
    character_name: 'Renegade',
    cost: 0,
    rarity: 'Commoner',
    description: '.',
    type: 'Character',
    unique_skill: 'Unknown',
    base_damage: 270,
    base_health: 200,
    chance_to_hit: 0.8,
    crit_chance: 0,
    crit_damage: 1.5,
  },
  // Add more card objects as needed
]

module.exports = CharacterList
